# Generated by Django 4.2 on 2023-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_auto_20231025_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourism',
            name='cost',
            field=models.CharField(max_length=10),
        ),
    ]
