# Generated by Django 4.2 on 2023-11-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='TotalCost',
            field=models.CharField(max_length=1000),
        ),
    ]
